### ISSUE TITLE
Uncompiled source

### ISSUE THREAD

**Issue by Haroenv** [anish000kumar/Voyager-vscode#1]
Hey! I'd love to contribute, but it seems like you only included the transpiled + minified source in the repo, could the original be added too? Thanks!

**Comment by anish000kumar** [comment]
@Haroenv The UI portion is basically a react app, will be pushing that as a separate repo by tomorrow.

**Comment by anish000kumar** [comment]
React repo link: https://github.com/anish000kumar/package-explorer-react
