### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by jm06487** [anish000kumar/Voyager-vscode#6]
Hello,
I first want to say that this is a great idea and has a lot of potentials.  Unfortunately, this is not working with the current version of VSC Insiders.  It has a blank screen when launched. 

- Thank You

**Comment by drmikecrowe** [comment]
Ditto

**Comment by cgunnels** [comment]
This is still an issue in Mar 2023.

**Comment by anish000kumar** [comment]
This extension is not actively maintained anymore, you can use "easy-npm" instead: https://marketplace.visualstudio.com/items?itemName=anish.easy-npm
